meta_product_name: "JoinTribe"
meta_title: "JoinTribe - Onboard your starters"
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
