meta_product_name: "JoinTribe"
meta_title: "JoinTribe - Onboard new starters"
meta_description: "Tribe offers the best way to help your new teamate to join your company"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
